// GENERATED by services/ai/scripts/codegen.py — do not hand-edit (Plan 02 overwrites this)
// Placeholder: minimal stub so the pnpm workspace link and apps/web import resolve now.
// Plan 02 codegen will replace this with the full pydantic-derived contract.

/**
 * 5-state absence/confidence flag for every extracted field.
 * Never collapses to blank — absence is first-class (D-07).
 */
export type FlagStatus =
  | "present"
  | "missing"
  | "unclear"
  | "conflicting"
  | "unsupported";
